config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "snowresorts#index"
  resources :snowresorts do
    resources :comments
    collection do
      get 'search'
    end
  end
  resources :users, only: [:show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :snowresort
end

app/models/snowresort.rb
class Snowresort < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_one_attached :image

  with_options presence: true do
    validates :resort_name
    validates :introduction
    validates :image
    validates :details
  end

  def self.search(search)
    if search != ""
      Snowresort.where('resort_name LIKE(?)', "%#{search}%")
    else
      Snowresort.all
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  has_many :snowresorts
  has_many :comments

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, uniqueness: true

  #with_options confirmation: true, format: { with: /\A(?=.*?[a-zA-Z])(?=.*?\d)[a-zA-Z\d]{6,}\z/, message: 'must be both letters and numbers' } do # 半角英数字含む６文字以上
   # validates :password
  #end

  with_options presence: true do
    validates :nickname
    validates :email
    validates :lastname
    validates :firstname
    validates :furigana_last
    validates :furigana_first
    validates :birthday
  end

  with_options format: { with: /\A[ぁ-んァ-ン一-龥]+\z/, message: 'must be Full-width' } do # 全角(漢字、カタカナ、ひらがな)指定
    validates :lastname
    validates :firstname
  end

  with_options format: { with: /\A[ァ-ヶー－]+\z/, message: 'must be Full-width katakana characters' } do   # 全角カタカナ指定
    validates :furigana_last
    validates :furigana_first
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :email, :lastname, :firstname, :furigana_last, :furigana_first, :birthday])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.create(comment_params)
    redirect_to "/snowresorts/#{@comment.snowresort.id}"
  end

  private
  def comment_params
    params.require(:comment).permit(:comment).merge(user_id: current_user.id, snowresort_id: params[:snowresort_id])
  end
end

app/controllers/snowresorts_controller.rb
class SnowresortsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit]
  before_action :snowresort_find, only: [:show, :edit, :update, :destroy]

  def index
    @snowresorts = Snowresort.all
  end

  def new 
    @snowresort = Snowresort.new
  end

  def create
    @snowresort = Snowresort.new(snowresort_params)
    if @snowresort.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @snowresort.comments.includes(:user)
  end

  def edit
    redirect_to root_path if current_user.id != @snowresort.user_id
  end

  def update
    if @snowresort.update(snowresort_params)
      redirect_to snowresort_path
    else
      render :edit
    end
  end

  def destroy
    if current_user.id == @snowresort.user_id
      @snowresort.destroy
      redirect_to root_path
    else
      redirect_to root_path
    end
  end

  def snowresort_find
    @snowresort = Snowresort.find(params[:id])
  end

  def search
    @snowresorts = Snowresort.search(params[:keyword])
  end

  private

  def snowresort_params
    params.require(:snowresort).permit(:image, :resort_name, :introduction, :details).merge user_id: current_user.id
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @nickname = current_user.nickname
    @snowresorts= current_user.snowresorts
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :email, :lastname, :firstname, :furigana_last, :furigana_first, :birthday)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/snowresorts_helper.rb
module SnowresortsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SnowresortApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= yield %>
    
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="post-footer">
    <ul class="menu">
      <li><a href="#">プライバシーポリシー</a></li>
      <li><a href="#">スノリゾルック利用規約</a></li>
    </ul>
  </footer>

app/views/shared/_header.html.erb
<header class="post-header">
  <%= link_to image_tag('logo.png', class:"logo"), "/" %>
</header>

app/views/snowresorts/edit.html.erb
<%= render "shared/header"%>

<div class="post-contents">
  <div class="post-main">
    <h2 class="post-title">スキー場の情報を入力</h2>
    <%= form_with model: @snowresort, local: true do |f| %>

    <%# インスタンスを渡して、エラー発生時にメッセージが表示されるようにしましょう。%>
    <%#= render 'shared/error_messages', model: f.object %>
  

    <%#　スキー場画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        スキー場画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>
    <%# /スキー場画像 %>
    <%# スキー場名と説明 %>
    <div class="new-snowresorts">
      <div class="weight-bold-text">
        スキー場名(正式名称で記入)
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :resort_name, class:"snowresorts-text", id:"resort-name", placeholder:"スキー場名（必須 正式名称でお願いします)", maxlength:"40" %>
      <div class="snowresort-explain">
        <div class="weight-bold-text">
          ゲレンデの説明
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :introduction, class:"snowresorts-text", id:"resort-info", placeholder:"ゲレンデの特徴（必須 1,000文字まで）（パークが充実、地形豊富、初心者向けなど）" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
    <%# /スキー場名と説明  %>
    <div class="snowresort-details">
      <div class="weight-bold-text">
        ゲレンデのコンディション
        <span class="indispensable">必須</span>
      </div>
        <%= f.text_area :details, class:"snowresorts-text", id:"resort-info", placeholder:"雪質、天候、混雑状況、リフト状況、積雪量など（必須 1,000文字まで）" ,rows:"7" ,maxlength:"1000" %>
    </div>

   
    <%# 下部ボタン %>
    <div class="post-btn-contents">
      <%= f.submit "投稿する" ,class:"post-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>
</div>

<%= render "shared/footer"%>

app/views/snowresorts/index.html.erb
<div class='title-contents'>
  <h2 class='title'>
    <%= link_to image_tag("logo.png", class:"logo-icon"), "/" %>
  </h2>
  <h2 class='service-title'>
    スノリゾルック
  </h2>
  <p class='service-explain'>
    スノーリゾート、スキー場を情報を
  </p>
  <p class='service-explain'>
    誰でも口コミ、検索ができます。
  </p>
  <ul class='lists-right'
    <% if user_signed_in? %>       
        <li><%= link_to current_user.nickname, "/users/#{current_user.id}", class: "user-nickname" %></li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>       
    <% else %>        
        <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
        <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
    <% end %>
  </ul>
  <%= button_to '投稿する', new_snowresort_path, method: :get, class: 'post' %>
  <div class='search-bar-contents'>
    <%= form_with(url: search_snowresorts_path, local: true, method: :get, class: "search-form") do |form| %>
      <%= form.text_field :keyword, placeholder: "キーワードからスキー場を検索", class: "input-box" %>
      <button class="search-button">
        <%= image_tag "search.png", class: "search-icon" %>
      </button>
    <% end %>
  </div>
  
  <div class='store-btn'>
    <%= link_to image_tag("https://linkmaker.itunes.apple.com/ja-jp/badge-lrg.svg?releaseDate=2011-09-21&kind=iossoftware&bubble=ios_apps", class:"apple-btn"), "#" %>
    <%= link_to image_tag("dl-android.png", class:"google-btn"), "#" %>
  </div>
</div>

  <%# 投稿一覧 %>
  <div class='snowresort-contents'>
    <h2 class='title'>ゲレンデ一覧</h2>
    <ul class='snowresort-lists'>
      <% @snowresorts.reverse.each do |snowresort|%>
        <li class='list'>
          <%= link_to snowresort_path(snowresort.id), method: :get do %>  
          <div class='resort-img-content'>
            <%= image_tag snowresort.image, class: "resort-img" %>
          </div>

          <div class='snowresort-info'>
            <div class="post-date">
              <!-- 投稿した時刻を出力する -->
              <%= l snowresort.created_at, format: :short %>
            </div>
            <h3 class='snowresort-name'>
              <%= snowresort.user.nickname%>
            </h3>
            <h3 class='snowresort-name'>
              <%= snowresort.resort_name %>
            </h3>
            <div class='star-btn'>
              <%= image_tag "star.png", class:"star-icon" %>
              <span class='star-count'>0</span>
            </div>
          </div>
          <% end %>  
        </li>
      <% end %> 
    </ul>
  </div>
  <%# 投稿一覧 %>

  <%= render "shared/footer"%>

app/views/snowresorts/new.html.erb
<%= render "shared/header"%>

<div class="post-contents">
  <div class="post-main">
    <h2 class="post-title">スキー場の情報を入力</h2>
    <%= form_with model: @snowresort, local: true do |f| %>

    <%# インスタンスを渡して、エラー発生時にメッセージが表示されるようにしましょう。%>
    <%#= render 'shared/error_messages', model: f.object %>
  

    <%#　スキー場画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        スキー場画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>
    <%# /スキー場画像 %>
    <%# スキー場名と説明 %>
    <div class="new-snowresorts">
      <div class="weight-bold-text">
        スキー場名(正式名称で記入)
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :resort_name, class:"snowresorts-text", id:"resort-name", placeholder:"スキー場名（必須 正式名称でお願いします)", maxlength:"40" %>
      <div class="snowresort-explain">
        <div class="weight-bold-text">
          ゲレンデの説明
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :introduction, class:"snowresorts-text", id:"resort-info", placeholder:"ゲレンデの特徴（必須 1,000文字まで）（パークが充実、地形豊富、初心者向けなど）" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
    <%# /スキー場名と説明  %>
    <div class="snowresort-details">
      <div class="weight-bold-text">
        ゲレンデのコンディション
        <span class="indispensable">必須</span>
      </div>
        <%= f.text_area :details, class:"snowresorts-text", id:"resort-info", placeholder:"雪質、天候、混雑状況、リフト状況、積雪量など（必須 1,000文字まで）" ,rows:"7" ,maxlength:"1000" %>
    </div>

   
    <%# 下部ボタン %>
    <div class="post-btn-contents">
      <%= f.submit "投稿する" ,class:"post-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>
</div>

<%= render "shared/footer"%>

app/views/snowresorts/search.html.erb
  <%= render "shared/header"%>
  
  <div class='search-bar-contents'>
    <%= form_with(url: search_snowresorts_path, local: true, method: :get, class: "search-form") do |form| %>
      <%= form.text_field :keyword, placeholder: "キーワードからスキー場を検索", class: "input-box" %>
      <button class="search-button">
        <%= image_tag "search.png", class: "search-icon" %>
      </button>
    <% end %>
  </div>
<div class="contents row">
  <ul class='snowresort-lists'>
    <% @snowresorts.reverse.each do |snowresort|%>
      <li class='list'>
        <%= link_to snowresort_path(snowresort.id), method: :get do %>  
          <div class='resort-img-content'>
            <%= image_tag snowresort.image, class: "resort-img" %>
          </div>

          <div class='snowresort-info'>
            <div class="post-date">
              <!-- 投稿した時刻を出力する -->
              <%= l snowresort.created_at, format: :short %>
            </div>
            <h3 class='snowresort-name'>
              <%= snowresort.user.nickname%>
            </h3>
            <h3 class='snowresort-name'>
              <%= snowresort.resort_name %>
            </h3>
            <div class='star-btn'>
              <%= image_tag "star.png", class:"star-icon" %>
              <span class='star-count'>0</span>
            </div>
          </div>
        <% end %>  
      </li>
    <% end %> 
  </ul>
</div>

<%= render "shared/footer"%>

app/views/snowresorts/show.html.erb
<%= render "shared/header"%>

<%# 投稿の概要 %>
<div class="resort-show">
    <h2 class="name">
      <%= @snowresort.resort_name %>
    </h2>
  <div class="resort-box">

    <div class='resort-img-content'>
      <%= image_tag @snowresort.image, class:"resort-box-img" %>
    </div>

    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">ゲレンデ紹介</th>
          <td class="detail-value"><%= @snowresort.introduction %></td>
        </tr>
        <tr>
          <th class="detail-item">コンディション</th>
          <td class="detail-value"><%= @snowresort.details %></td>
        </tr>
        <tr>
          <th class="detail-item">投稿者</th>
          <td class="detail-value"><%= @snowresort.user.nickname %></td>
        </tr>
        <tr>
          <th class="detail-item">投稿時間</th>
          <td class="detail-value"><%= l @snowresort.created_at, format: :short %></td>
        </tr>
      </tbody>
    </table>
    <div class="option">
      <div class="favorite-btn">
        <%= image_tag "star.png" ,class:"favorite-star-icon" ,width:"20",height:"20"%>
        <span>お気に入り 0</span>
      </div>
    </div>
  </div>
  <div class="henshuu">
    <% if user_signed_in?%>
      <% if current_user.id == @snowresort.user_id %>
        <%= link_to '投稿の編集', edit_snowresort_path(@snowresort.id), method: :get, class: "resort-blue-btn" %>
        <%= link_to '削除', snowresort_path(@snowresort.id), method: :delete, class:'resort-destroy' %>
      <% end %>
    <% end %>
  </div>  

  <%# /投稿の概要 %>

  <%# コメント欄 %>
  <div class="comment-box">
    <% if user_signed_in? %>
      <%= form_with(model: [@snowresort, @comment], local: true) do |form| %>
        <%= form.text_area :comment, placeholder: "コメントする", class: "comment-text"%>
        <button type="submit" class="comment-btn">
          <span>コメントする<span>
        </button>
      <% end %>
    <% else %>
      <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong>
    <% end %>
  </div>

  <div class="comments">
    <h4>＜コメント一覧＞</h4>
    <% @comments.reverse.each do |comment| %>
      <div class="post-comment">
        <strong><%= link_to comment.user.nickname, "/users/#{comment.user_id}" %>：</strong>
        <%= comment.comment %>
        <div class="comment-date">
          <%= l comment.created_at, format: :short %>
        </div>
      </div>
    <% end %>
  </div>
</div>
<%# /コメント欄 %>

<%= render "shared/footer" %>   

app/views/users/edit.html.erb
<%= render "shared/header"%>

<%= form_with model: current_user, class: 'registration-main', local: true do |f| %>

<div class='form-wrap'>
  <div class='form-header'>
    <h1 class='form-header-text'>
      登録情報の変更
    </h1>
  </div>

  <%# インスタンスを渡して、エラー発生時にメッセージが表示されるようにしましょう。%>
  <%= render 'shared/error_messages', model: f.object %>
  <%# //インスタンスを渡して、エラー発生時にメッセージが表示されるようにしましょう。%>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">ニックネーム</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_area :nickname, class:"input-default", id:"nickname", placeholder:"例) 岡田太郎", maxlength:"40" %>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">メールアドレス</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.email_field :email, class:"input-default", id:"email", placeholder:"PC・携帯どちらでも可", autofocus: true %>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">パスワード</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.password_field :password, class:"input-default", id:"password", placeholder:"6文字以上の半角英数字" %>
    <p class='info-text'>※英字と数字の両方を含めて設定してください</p>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">パスワード(確認)</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.password_field :password_confirmation, class:"input-default", id:"password-confirmation", placeholder:"同じパスワードを入力して下さい" %>
  </div>
  
  <div class="form-group">
    <p class='form-info-header'>
      本人確認
    </p>
    <p class='form-info-text'>
      安心・安全にご利用いただくために、お客さまの本人情報の登録にご協力ください。他のお客さまに公開されることはありません。
    </p>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">お名前(全角)</label>
      <span class="indispensable">必須</span>
    </div>
    <div class='input-name-wrap'>
      <%= f.text_area :lastname, class:"input-name", id:"last-name", placeholder:"例) 山田" %>
      <%= f.text_area :firstname, class:"input-name", id:"first-name", placeholder:"例) 陸太郎" %>
    </div>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">お名前カナ(全角)</label>
      <span class="indispensable">必須</span>
    </div>
    <div class='input-name-wrap'>
      <%= f.text_area :furigana_last, class:"input-name", id:"last-name-kana", placeholder:"例) ヤマダ" %>
      <%= f.text_area :furigana_first, class:"input-name", id:"first-name-kana", placeholder:"例) リクタロウ" %>
    </div>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">生年月日</label>
      <span class="indispensable">必須</span>
    </div>
    <div class='input-birth-wrap'>
      <%= raw sprintf(
                  f.date_select(
                    :birthday,
                    class:'select-birth',
                    id:"birth-date",
                    use_month_numbers: true,
                    prompt:'--',
                    start_year: 1930,
                    end_year: (Time.now.year - 5),
                    date_separator: '%s'),
                  "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" %>
    </div>
    <p class='info-text'>※ 本人情報は正しく入力してください。会員登録後、修正するにはお時間を頂く場合があります。</p>
  </div>
  <div class="form-group">
    <h2 class='form-bottom-text'>
      「会員登録」のボタンを押すことにより、
      <span>利用規約</span>
      <br>に同意したものとみなします
    </h2>
  </div>
  <div class='register-btn'>
    <%= f.submit "登録内容の更新" ,class:"register-red-btn" %>
  </div>
  <p class='register-info'>本人情報の登録について</p>
</div>
<% end %>

<%= render"shared/footer"%>

app/views/users/show.html.erb
<%= render "shared/header"%>

<div class="profile">
  <%= link_to "プロフィールの変更", edit_user_path(current_user) %>
</div>
<p class='title2'><%= @nickname %>さんの投稿一覧</p>
<div class="snowresort-contents">
  
  <% @snowresorts.reverse.each do |snowresort| %>
    <%= image_tag snowresort.image, class: "resort-img" %>
    <%= l snowresort.created_at, format: :short %>
      <p><%= snowresort.resort_name %></p>
    </div>
  <% end %>
</div>